# Generated by Django 3.0.6 on 2020-05-13 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=30)),
                ('moved_by', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('goal_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='benpelumiscrumy.GoalStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ScrumyGoals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_by', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=30)),
                ('moved_from', models.CharField(max_length=50)),
                ('moved_to', models.CharField(max_length=50)),
                ('time_of_action', models.DateField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='benpelumiscrumy.ScrumyGoals')),
            ],
        ),
    ]
