# Generated by Django 3.0.6 on 2020-05-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benpelumiscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='goal_id',
            field=models.IntegerField(default='1'),
        ),
    ]
