# Generated by Django 3.0.6 on 2020-06-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benpelumiscrumy', '0011_auto_20200603_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_id',
            field=models.IntegerField(null=True),
        ),
    ]
